name: publish

on:
  workflow_dispatch:
    inputs:
      package:
        description: Package to publish
        required: true
        default: eslint-config
  release:
    types:
      - published

jobs:
  generic_publish:
    name: Publish ${{ matrix.package }} to ${{ matrix.registry.name }} Registry
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - eslint-config
          - prettier-config
          - tsconfig
        registry:
          - name: NPM
            url: https://registry.npmjs.org
            token: ${{ secrets.NPM_TOKEN }}
          - name: Github Package
            url: https://npm.pkg.github.com
            token: ${{ secrets.GITHUB_TOKEN }}
    env:
      PACKAGE_NAME: ${{ github.event.inputs.package || github.event.release.name }}
    defaults:
      run:
        working-directory: packages/${{ matrix.package }}
    steps:
      - uses: actions/checkout@v2
        if: ${{ contains(env.PACKAGE_NAME, matrix.package) }}
      - uses: actions/setup-node@v1
        if: ${{ contains(env.PACKAGE_NAME, matrix.package) }}
        with:
          node-version: 14
          registry-url: ${{ matrix.registry.url }}
      - run: yarn install
        if: ${{ contains(env.PACKAGE_NAME, matrix.package) }}
      - run: yarn publish
        if: ${{ contains(env.PACKAGE_NAME, matrix.package) }}
        env:
          NODE_AUTH_TOKEN: ${{ matrix.registry.token }}
